if (__OPENSSL_INCLUDED)
    return()
endif (__OPENSSL_INCLUDED)
set(__OPENSSL_INCLUDED TRUE)

option(ENABLE_TLS "use OpenSSL (enabled)" ON)
if (NOT ENABLE_TLS)
    return()
endif (NOT ENABLE_TLS)

include(utils)
sofia_include_file(openssl/tls1.h)

# Check Whether enable tls
find_package(PkgConfig REQUIRED)
pkg_check_modules(OPENSSL openssl)
if (OPENSSL_FOUND)
    set(HAVE_LIBCRYPTO 1)
    set(HAVE_OPENSSL   1)
    set(HAVE_LIBSSL    1)
    set(HAVE_TLS       1)
    link_libraries(${OPENSSL_LIBRARIES})
else (OPENSSL_FOUND)
    if (HAVE_OPENSSL_TLS1_H)
        sofia_library_exists(crypto BIO_new HAVE_OPENSSL)
        if (NOT HAVE_OPENSSL)
            message(WARNING "OpenSSL crypto library was not found")
        endif (NOT HAVE_OPENSSL)
        sofia_library_exists(ssl TLSv1_method HAVE_TLS)
        if (NOT HAVE_TLS)
            message(WARNING "OpenSSL protocol library was not found")
        endif (NOT HAVE_TLS)
    else (HAVE_OPENSSL_TLS1_H)
        message(WARNING "OpenSSL include files were not found")
    endif (HAVE_OPENSSL_TLS1_H)
endif (OPENSSL_FOUND)
