name: Deb packages

on:
  push:
    branches: [ master ] 
    
jobs:

  sofia_build:
    permissions: write-all
    name: 'Build'
    uses: signalwire/actions-template/.github/workflows/ci-deb-packages.yml@feat/deb
    with:
      PROJECT_NAME: sofia-sip
      RUNNER: ubuntu-latest
      AUTHOR_EMAIL: lucas.carlos@signalwire.com
      TARGET_BRANCH: master
    secrets: inherit 
  
