name: Deb packages

on:
  push:
    branches: [ master ] 
    
jobs:

  sofia_build:
    name: 'Build'
    permissions: write-all
    uses: signalwire/actions-template/.github/workflows/ci-deb-packages.yml@feat/deb
    with:
      PROJECT_NAME: sofia-sip
      RUNNER: ubuntu-latest
      AUTHOR_EMAIL: lucas.carlos@signalwire.com
      TARGET_BRANCH: master
      OS_FAMILIES: stretch,bullseye,buster 
    secrets: 
      PAT: ${{ secrets.PAT }}
  
  # distribute_matrix:
  #   permissions: write-all
  #   name: 'Copy to remote'
  #   needs: sofia_build
  #   strategy:
  #     matrix:
  #       target_path: 
  #         - /var/www/fsa/repo/deb/fsa/incoming
  #         - /var/www/fsa/repo/debian/release/incoming
  #         - /var/www/fsa/repo/debian/unstable/incoming
  #         - /var/www/repo/deb/freeswitch-1.8/incoming
  #         - /var/www/deb-public-unstable/incoming
    
  #   uses: signalwire/actions-template/.github/workflows/cd-scp.yml@main
  #   with:
  #     ARTIFACT_NAME: rpm-artifact
  #     TARGET_FOLDER: ${{ matrix.target_path }}
  #     RUNNER: ubuntu-latest
  #     EXEC_COMMANDS: find ${{ matrix.target_path }} -type f -name "*.tar.gz" -exec mv "{}" "{}".unlocked \;
  #     FILES: '*.tar.gz *.sha1'
  #   secrets: 
  #     # Explicit define secrets for better understanding but it could be just inherit 
  #     PROXY_URL: ${{ secrets.PROXY_URL }}
  #     USERNAME: ${{ secrets.USERNAME }}
  #     HOSTNAME: ${{ secrets.HOSTNAME }}
  #     TELEPORT_TOKEN: ${{ secrets.TELEPORT_TOKEN }}