name: Deb packages

on:
  push:
    branches: [ master ] 
    
jobs:

  sofia_build:
    name: 'Build'
    uses: signalwire/actions-template/.github/workflows/ci-deb-packages.yml@feat/deb
    with:
      PROJECT_NAME: sofia-sip
      RUNNER: ubuntu-latest
    secrets: inherit 
  
