name: RPM packages

on:
  push:
    branches: [ master ] 
    
jobs:

  sofia_build:
    name: 'Build'
    uses: signalwire/actions-template/.github/workflows/ci-rpm-packages.yml@main
    with:
      PROJECT_NAME: sofia-sip
      RUNNER: ubuntu-latest
      PACKAGER: 'packager Andrey Volk <andrey@signalwire.com>'
    secrets: inherit 
  
  distribute_matrix:
    permissions: write-all
    name: 'Copy to remote'
    needs: sofia_build
    strategy:
      matrix:
        target_path: 
          - /var/www/repo/yum/centos-release/7
          - /var/www/fsa/repo/yum-stack/fsa/centos-release/7
          - /var/www/repo/yum/centos-dev/7
          - /var/www/fsa/repo/yum-stack/fsa/centos-dev/7
    
    uses: signalwire/actions-template/.github/workflows/cd-scp.yml@main
    with:
      ARTIFACT_NAME: rpm-artifact
      TARGET_FOLDER: ${{ matrix.target_path }}
      RUNNER: ubuntu-latest
      EXEC_COMMANDS: find ${{ matrix.target_path }} -type f -name "*.tar.gz" -exec mv "{}" "{}".unlocked \;
      FILES: '*.tar.gz *.sha1'
    secrets: 
      # Explicit define secrets for better understanding but it could be just inherit 
      PROXY_URL: ${{ secrets.PROXY_URL }}
      USERNAME: ${{ secrets.USERNAME }}
      HOSTNAME: ${{ secrets.HOSTNAME }}
      TELEPORT_TOKEN: ${{ secrets.TELEPORT_TOKEN }}
